export default {
  useReset: true,
  useVariable: true,
  useFontImport: true,
  useIconSprite: true,
  useSvgSprite: true,
  useDefaultConfig: true,
  useDocumentTheme: true,
  verbose: false,

  polyglot: {
    defaultLang: 'en',
    languages: ['en'],
    storageLangKey: 'zse_lang',
    storagePrefix: 'zse_t_',
    translations: {
      en: {
        appMetaTitle: 'Zero Sum Entertainment',
        appMetaDescription: 'Guess how far off the attempt lands. Closest ten percent split the pot.',
        brandName: 'Zero Sum Entertainment',

        pickerKicker: 'Zero Sum · Live betting',
        pickerTitle: 'Pick your game',
        pickerLead:
          'A host attempts a precise physical task. You bet on how far off it lands. The closest guesses split the pot.',
        pickerHonesty:
          'Once betting locks, nothing can change — not the bets, not the crowd, not the pot, not the result.',
        bananaKicker: 'Two scales · one cut',
        bananaTitle: 'Banana Cut',
        bananaObjective:
          'One cut, exactly in half. Bet on how many grams off the two halves land.',
        bananaRange: 'Guess −20 to +20 g',
        bananaPosterAlt: 'A banana on two kitchen scales next to a knife',
        waterKicker: 'One glass · 200 g',
        waterTitle: 'Water Pour',
        waterObjective:
          'One pour, exactly 200 g. Bet on how many grams off the pour lands.',
        waterRange: 'Guess −50 to +50 g',
        waterPosterAlt: 'A host holding a water bottle over an empty glass on a scale',
        gameStake: 'Fixed stake 20 chips',
        playNow: 'Play',

        demoBadge: 'Demo · simulated crowd',
        roundWord: 'Round',
        ofWord: 'of',
        introWatch: '— watch',
        exitStage: 'Exit',

        timerPreview: 'Bets open in',
        timerBetting: 'Bets close in',
        timerLocked: 'Locked',
        timerResults: 'Next round in',

        rakeNote: 'Closest 10% split the pot · 5% rake · 20 chips',

        crowdTitle: 'The crowd',
        liveBadge: 'Live',
        lockedBadge: 'Locked',
        lockedNote: 'Frozen at lock — nothing can change',
        arrivedVerb: 'is in',
        playersLabel: 'Players',
        potLabel: 'Pot',
        chipsUnit: 'chips',

        betPrompt: 'How far off?',
        scaleExact: 'exact',
        placeBet: 'Place bet · 20 chips',
        betPlaced: 'Bet placed',
        betsLocked: 'Bets locked',
        yourGuess: 'Your guess',

        lockedStamp: 'Locked',
        lockedPromise: 'Bets, crowd, pot — frozen. Watch.',
        revealWatching: 'Locked · watching',

        historyTitle: 'Last results',
        historyEmpty: 'No rounds yet',

        resultKicker: 'Result',
        scaleSaid: 'The scale said',
        histogramTitle: 'Where the crowd stood',
        legendResult: 'result',
        legendMine: 'you',
        winnerOne: 'player nailed it',
        winnerMany: 'players nailed it',
        youWon: 'You won',
        notThisTime: 'Not this time. Next round is seconds away.',
        noBetNote: 'You sat this one out.',
        playersMeta: 'players',
        potMeta: 'pot',
        rakeMeta: 'rake',
        multiplierMeta: 'multiplier',

        sessionKicker: 'Session over',
        statRounds: 'Rounds',
        statNet: 'Your net',
        statBest: 'Best multiplier',
        playAgain: 'Play again',
        otherGame: 'Choose another game',

        balanceLabel: 'Balance',

        // ---- workspace console ------------------------------------------
        wsMetaTitle: 'Workspace · Zero Sum Entertainment',
        wsMetaDescription: 'Analytics and management console for Zero Sum Entertainment.',
        wsBrand: 'Workspace',
        wsBrandSub: 'Operator console',
        wsOpenWorkspace: 'Workspace',
        wsBackToGame: '← Back to game',
        wsNavOverview: 'Overview',
        wsNavLive: 'Live',
        wsNavRounds: 'Rounds',
        wsNavRound: 'Round detail',
        wsNavBets: 'Bets',
        wsNavPlayers: 'Players',
        wsNavLedger: 'Ledger',
        wsNavGames: 'Games',
        wsNavIntegrity: 'Integrity',
        wsSourceDemo: 'DEMO STORE',
        wsSourceServer: 'SUPABASE',
        wsSourceNone: 'NO SOURCE',
        wsLastRefresh: 'Refreshed',
        wsNeverRefreshed: 'never',
        wsRefresh: 'Refresh',
        wsExportCsv: 'Export CSV',
        wsResetDemo: 'Reset demo',
        wsSure: 'Sure?',
        wsStaffOnly: 'Staff only',
        wsLoading: 'Loading',
        wsDismiss: 'Dismiss',

        wsKpiRounds: 'Rounds',
        wsKpiBets: 'Bets',
        wsKpiStaked: 'Staked',
        wsKpiPaidOut: 'Paid out',
        wsKpiHouse: 'House take',
        wsKpiPlayers: 'Players',
        wsKpiAvgMult: 'Avg multiplier',
        wsKpiBestMult: 'Best multiplier',
        wsConservationOk: 'All rounds conserved',
        wsConservationBreach: 'Conservation breach',
        wsBreachesWord: 'rounds off',
        wsConservationNote: 'stakes = prize + house, every settled round',
        wsChartPot: 'Pot per round',
        wsChartMultiplier: 'Multiplier per round',
        wsChartPlayers: 'Players per round',
        wsChartEmpty: 'No data yet',

        wsLiveTitle: 'Live rounds',
        wsLiveEmpty: 'No active game — open the game to start a round.',
        wsFrozen: 'Frozen at lock',
        wsSecondsLeft: 'seconds left',
        wsRoundWord: 'Round',

        wsRoundsTitle: 'Rounds',
        wsRoundsEmpty: 'No rounds yet — play a game.',
        wsColGame: 'Game',
        wsColIndex: '#',
        wsColResult: 'Result',
        wsColReadings: 'Readings',
        wsColPlayers: 'Players',
        wsColPot: 'Pot',
        wsColPrize: 'Prize',
        wsColWinners: 'Winners',
        wsColPayout: 'Payout',
        wsColMultiplier: '×',
        wsColHouse: 'House',
        wsColSettled: 'Settled',
        wsColConserved: 'Conserved',
        wsColPhase: 'Phase',
        wsColPlayer: 'Player',
        wsColGuess: 'Guess',
        wsColDistance: 'Distance',
        wsColWon: 'Won',
        wsColPlaced: 'Placed',
        wsColBalance: 'Balance',
        wsColBets: 'Bets',
        wsColWins: 'Wins',
        wsColStaked: 'Staked',
        wsColPaidOut: 'Paid out',
        wsColNet: 'Net',
        wsColAt: 'At',
        wsColKind: 'Kind',
        wsColAmount: 'Amount',
        wsColRound: 'Round',
        wsColLedgerSum: 'Σ ledger',
        wsColOk: 'OK',
        wsColStatus: 'Status',
        wsColCheck: 'Check',
        wsColDetail: 'Detail',

        wsBackToRounds: '← Rounds',
        wsRoundDetailEmpty: 'Select a round from the Rounds table.',
        wsVoidRound: 'Void round',
        wsVoided: 'Voided',
        wsSealed: 'sealed until reveal',
        wsSealedNote: 'Guesses are sealed until reveal — counts and pot only.',
        wsDistributionTitle: 'Guess distribution',
        wsBetsTitle: 'Bets',
        wsBetsEmpty: 'No bets match.',
        wsYes: 'yes',
        wsNo: 'no',
        wsBot: 'BOT',
        wsHouse: 'HOUSE',
        wsFilterGame: 'Game',
        wsFilterRound: 'Round',
        wsFilterPlayer: 'Player',
        wsFilterWon: 'Won',
        wsFilterAll: 'All',
        wsFilterWonOnly: 'Won',
        wsFilterLostOnly: 'Lost',
        wsClearFilters: 'Clear',

        wsPlayersTitle: 'Leaderboard',
        wsPlayersEmpty: 'No players yet.',

        wsLedgerTitle: 'Chip ledger',
        wsLedgerEmpty: 'No ledger entries yet.',
        wsKindAll: 'All',
        wsKindGrant: 'grant',
        wsKindStake: 'stake',
        wsKindPayout: 'payout',
        wsKindRake: 'rake',
        wsKindRefund: 'refund',
        wsAuditTitle: 'Ledger audit',
        wsAuditOk: 'Σ ledger = balance for every player',
        wsAuditFail: 'Ledger and balances disagree',
        wsAuditEmpty: 'Nothing to audit yet.',

        wsGamesTitle: 'Games',
        wsGamesEmpty: 'No games configured.',
        wsActive: 'Active',
        wsInactive: 'Inactive',
        wsRange: 'Range',
        wsStep: 'Step',
        wsUnit: 'Unit',
        wsVideo: 'Video',
        wsScripts: 'Round scripts',
        wsScheduleRound: 'Schedule round',
        wsServerOnly: 'Server only',
        wsTlBetOpen: 'bet open',
        wsTlReveal: 'reveal',
        wsTlPause: 'pause',
        wsTlResult: 'result',

        wsIntegrityTitle: 'Integrity checks',
        wsIntegrityEmpty: 'No checks reported yet.',
        wsStatusPass: 'pass',
        wsStatusFail: 'fail',
        wsStatusNa: 'n/a',
        wsStatusUnknown: 'unknown'
      }
    }
  }
}
