export default {
  useReset: true,
  useVariable: true,
  useFontImport: true,
  useIconSprite: true,
  useSvgSprite: true,
  useDefaultConfig: true,
  useDocumentTheme: true,
  verbose: false,

  polyglot: {
    defaultLang: 'en',
    languages: ['en'],
    storageLangKey: 'zse_lang',
    storagePrefix: 'zse_t_',
    translations: {
      en: {
        appMetaTitle: 'Zero Sum Entertainment',
        appMetaDescription: 'Two challengers, one task. Bet on who lands closer. Back the winner, split the pot.',
        brandName: 'Zero Sum Entertainment',

        pickerKicker: 'Zero Sum · Live betting',
        pickerTitle: 'Pick your game',
        pickerLead:
          'Two challengers, one task. Bet on who lands closer. Winners split the pot.',
        pickerHonesty:
          'Once bets lock, nothing can change.',
        bananaKicker: 'One cut each',
        bananaTitle: 'Banana Cut',
        bananaObjective:
          'Cut a banana in half. Whose halves are closest to equal?',
        bananaPosterAlt: 'A banana on two kitchen scales next to a knife',
        waterKicker: '200 g by eye',
        waterTitle: 'Water Pour',
        waterObjective:
          'Pour 200 g by eye. Who lands closer?',
        waterPosterAlt: 'A host holding a water bottle over an empty glass on a scale',
        gameStake: '20 chips a bet',
        playNow: 'Play',

        demoBadge: 'Demo crowd',
        roundWord: 'Duel',
        ofWord: 'of',
        sideWord: 'Side',
        offWord: 'off',
        deadHeat: 'Dead heat',
        deadHeatNote: 'Dead heat. Stakes refunded.',
        winsVerb: 'wins',
        exitStage: 'Exit',

        timerPreview: 'Bets open in',
        timerBetting: 'Bets close in',
        timerLocked: 'Locked',
        timerResults: 'Next duel in',

        rakeNote: '20 chips · winners split the pot · 5% rake',

        crowdTitle: 'The crowd',
        liveBadge: 'Live',
        lockedBadge: 'Locked',
        lockedNote: 'Frozen at lock.',
        arrivedVerb: 'is in',
        playersLabel: 'Players',
        potLabel: 'Pot',
        chipsUnit: 'chips',

        betPrompt: 'Who lands closer?',
        placeBet: 'Place bet · 20 chips',
        betPlaced: 'Bet placed',
        betsLocked: 'Bets locked',
        soundOn: 'Sound on',
        soundOff: 'Sound off',
        pickFirst: 'Pick a challenger first',
        betsOpenSoon: 'Bets open after the countdown',
        yourPick: 'Your pick',

        lockedStamp: 'Locked',
        lockedPromise: 'Nothing changes now.',
        revealWatching: 'Locked',

        historyTitle: 'Last results',
        historyEmpty: 'No rounds yet',

        resultKicker: 'Result',
        legendResult: 'winner',
        youWon: 'You won',
        youLost: 'Not this time',
        youBacked: 'You backed',
        winnerOne: 'winner takes the pot',
        winnerMany: 'winners split the pot',
        voidTitle: 'Dead heat',
        voidNote: 'Stakes refunded, no rake.',
        noBetNote: 'You sat this one out.',
        nextDuelNote: 'Next duel soon.',
        playersMeta: 'players',
        potMeta: 'pot',
        rakeMeta: 'rake',
        multiplierMeta: 'multiplier',

        sessionKicker: 'Session over',
        statRounds: 'Duels',
        statNet: 'Your net',
        statBest: 'Best payout',
        playAgain: 'Play again',
        otherGame: 'Other game',

        balanceLabel: 'Balance',

        // ---- workspace console ------------------------------------------
        wsMetaTitle: 'Workspace · Zero Sum Entertainment',
        wsMetaDescription: 'Analytics and management console for Zero Sum Entertainment.',
        wsBrand: 'Workspace',
        wsBrandSub: 'Operator console',
        wsOpenWorkspace: 'Workspace',
        wsBackToGame: '← Back to game',
        wsNavOverview: 'Overview',
        wsNavLive: 'Live',
        wsNavRounds: 'Rounds',
        wsNavRound: 'Round detail',
        wsNavBets: 'Bets',
        wsNavPlayers: 'Players',
        wsNavLedger: 'Ledger',
        wsNavGames: 'Games',
        wsNavIntegrity: 'Integrity',
        wsSourceDemo: 'DEMO STORE',
        wsSourceServer: 'SUPABASE',
        wsSourceNone: 'NO SOURCE',
        wsLastRefresh: 'Refreshed',
        wsNeverRefreshed: 'never',
        wsRefresh: 'Refresh',
        wsExportCsv: 'Export CSV',
        wsResetDemo: 'Reset demo',
        wsSure: 'Sure?',
        wsStaffOnly: 'Staff only',
        wsLoading: 'Loading',
        wsDismiss: 'Dismiss',

        wsKpiRounds: 'Rounds',
        wsKpiBets: 'Bets',
        wsKpiStaked: 'Staked',
        wsKpiPaidOut: 'Paid out',
        wsKpiHouse: 'House take',
        wsKpiPlayers: 'Players',
        wsKpiAvgMult: 'Avg multiplier',
        wsKpiBestMult: 'Best multiplier',
        wsConservationOk: 'All rounds conserved',
        wsConservationBreach: 'Conservation breach',
        wsBreachesWord: 'rounds off',
        wsConservationNote: 'stakes = prize + house, every settled round',
        wsChartPot: 'Pot per round',
        wsChartMultiplier: 'Multiplier per round',
        wsChartPlayers: 'Players per round',
        wsChartEmpty: 'No data yet',

        wsLiveTitle: 'Live rounds',
        wsLiveEmpty: 'No active game — open the game to start a round.',
        wsFrozen: 'Frozen at lock',
        wsSecondsLeft: 'seconds left',
        wsRoundWord: 'Round',

        wsRoundsTitle: 'Rounds',
        wsRoundsEmpty: 'No rounds yet — play a game.',
        wsColGame: 'Game',
        wsColIndex: '#',
        wsColResult: 'Winner',
        wsColReadings: 'Readings',
        wsColPlayers: 'Players',
        wsColPot: 'Pot',
        wsColPrize: 'Prize',
        wsColWinners: 'Winners',
        wsColPayout: 'Payout',
        wsColMultiplier: '×',
        wsColHouse: 'House',
        wsColSettled: 'Settled',
        wsColConserved: 'Conserved',
        wsColPhase: 'Phase',
        wsColPlayer: 'Player',
        wsColGuess: 'Pick',
        wsColWon: 'Won',
        wsColPlaced: 'Placed',
        wsColBalance: 'Balance',
        wsColBets: 'Bets',
        wsColWins: 'Wins',
        wsColStaked: 'Staked',
        wsColPaidOut: 'Paid out',
        wsColNet: 'Net',
        wsColAt: 'At',
        wsColKind: 'Kind',
        wsColAmount: 'Amount',
        wsColRound: 'Round',
        wsColLedgerSum: 'Σ ledger',
        wsColOk: 'OK',
        wsColStatus: 'Status',
        wsColCheck: 'Check',
        wsColDetail: 'Detail',

        wsBackToRounds: '← Rounds',
        wsRoundDetailEmpty: 'Select a round from the Rounds table.',
        wsVoidRound: 'Void round',
        wsVoided: 'Voided',
        wsSealed: 'sealed until reveal',
        wsSealedNote: 'Guesses are sealed until reveal — counts and pot only.',
        wsDistributionTitle: 'Crowd split',
        wsBetsTitle: 'Bets',
        wsBetsEmpty: 'No bets match.',
        wsYes: 'yes',
        wsNo: 'no',
        wsBot: 'BOT',
        wsHouse: 'HOUSE',
        wsFilterGame: 'Game',
        wsFilterRound: 'Round',
        wsFilterPlayer: 'Player',
        wsFilterWon: 'Won',
        wsFilterAll: 'All',
        wsFilterWonOnly: 'Won',
        wsFilterLostOnly: 'Lost',
        wsClearFilters: 'Clear',

        wsPlayersTitle: 'Leaderboard',
        wsPlayersEmpty: 'No players yet.',

        wsLedgerTitle: 'Chip ledger',
        wsLedgerEmpty: 'No ledger entries yet.',
        wsKindAll: 'All',
        wsKindGrant: 'grant',
        wsKindStake: 'stake',
        wsKindPayout: 'payout',
        wsKindRake: 'rake',
        wsKindRefund: 'refund',
        wsAuditTitle: 'Ledger audit',
        wsAuditOk: 'Σ ledger = balance for every player',
        wsAuditFail: 'Ledger and balances disagree',
        wsAuditEmpty: 'Nothing to audit yet.',

        wsGamesTitle: 'Games',
        wsGamesEmpty: 'No games configured.',
        wsActive: 'Active',
        wsInactive: 'Inactive',
        wsSides: 'Sides',
        wsChallenger: 'Challenger',
        wsDeadHeat: 'Dead heat',
        wsUnit: 'Unit',
        wsVideo: 'Video',
        wsScripts: 'Round scripts',
        wsScheduleRound: 'Schedule round',
        wsServerOnly: 'Server only',
        wsTlLock: 'lock',
        wsTlReveal1: 'C1 read',
        wsTlReveal2: 'C2 read',
        wsTlEnd: 'end',
        wsTlResult: 'winner',

        wsIntegrityTitle: 'Integrity checks',
        wsIntegrityEmpty: 'No checks reported yet.',
        wsStatusPass: 'pass',
        wsStatusFail: 'fail',
        wsStatusNa: 'n/a',
        wsStatusUnknown: 'unknown'
      }
    }
  }
}
